Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 28
Metrics/MethodLength:
  Max: 16
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 10
Layout/LineLength:
  Max: 82

  